name: Branch Build

on: [ push ]

jobs:
  branch-build:
    strategy:
      matrix:
        go-version: [1.14.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Ensure proto library is updated
      run : ./proto/regen-protos.sh
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...
